# Generated by Django 5.2.5 on 2026-08-12 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_image', models.URLField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(allow_unicode=True, max_length=220, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='categories/')),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('badge', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('wordpress_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category')),
            ],
            options={
                'ordering': ('sort_order', 'name'),
                'indexes': [models.Index(fields=['parent', 'is_active'], name='categories__parent__85acd9_idx')],
            },
        ),
    ]
