# Generated by Django 5.2.5 on 2026-08-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='banners/')),
                ('mobile_image', models.ImageField(blank=True, upload_to='banners/mobile/')),
                ('link', models.CharField(blank=True, max_length=500)),
                ('position', models.CharField(choices=[('hero', 'hero'), ('quick_access', 'quick_access'), ('specialized', 'specialized'), ('splash', 'splash'), ('row', 'row'), ('bottom', 'bottom'), ('sidebar', 'sidebar'), ('offers_top', 'offers_top'), ('offers_golden', 'offers_golden'), ('new_arrivals_top', 'new_arrivals_top'), ('new_arrivals_vertical', 'new_arrivals_vertical'), ('new_arrivals_bottom', 'new_arrivals_bottom'), ('bestsellers_vertical', 'bestsellers_vertical')], db_index=True, max_length=32)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('badge_text', models.CharField(blank=True, max_length=80)),
                ('button_text', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ('position', 'order'),
            },
        ),
    ]
