# Generated by Codex on 2026-08-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickAccessItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                ("icon", models.CharField(blank=True, max_length=255)),
                ("image", models.ImageField(blank=True, upload_to="homepage/quick-access/")),
                ("url", models.CharField(blank=True, max_length=500)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("badge", models.CharField(blank=True, max_length=80)),
            ],
            options={"ordering": ("order", "id")},
        ),
        migrations.CreateModel(
            name="ProductGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(allow_unicode=True, max_length=180, unique=True)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="homepage/product-groups/")),
                ("icon", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("products", models.ManyToManyField(blank=True, related_name="homepage_groups", to="products.product")),
            ],
            options={"ordering": ("order", "id")},
        ),
        migrations.CreateModel(
            name="ProductSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(allow_unicode=True, max_length=180, unique=True)),
                ("section_type", models.CharField(choices=[("highlights", "Highlights"), ("offers", "Offers"), ("new_arrivals", "New arrivals"), ("best_sellers", "Best sellers"), ("most_popular", "Most popular")], db_index=True, max_length=32)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                ("badge", models.CharField(blank=True, max_length=80)),
                ("display_type", models.CharField(choices=[("carousel", "Carousel"), ("grid", "Grid"), ("slider", "Slider"), ("list", "List")], default="carousel", max_length=20)),
                ("max_products", models.PositiveIntegerField(default=8)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("products", models.ManyToManyField(blank=True, related_name="homepage_sections", to="products.product")),
            ],
            options={"ordering": ("order", "id")},
        ),
        migrations.AddIndex(model_name="productsection", index=models.Index(fields=["section_type", "slug", "is_active"], name="homepage_pr_section_1fe0f4_idx")),
    ]
