# Generated by Django 5.2.5 on 2026-08-12 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total', models.PositiveBigIntegerField(default=0)),
                ('discount', models.PositiveBigIntegerField(default=0)),
                ('shipping_cost', models.PositiveBigIntegerField(default=0)),
                ('payment_status', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('failed', 'failed'), ('refunded', 'refunded')], default='pending', max_length=30)),
                ('order_status', models.CharField(choices=[('draft', 'draft'), ('pending_payment', 'pending_payment'), ('processing', 'processing'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='pending_payment', max_length=30)),
                ('shipping_status', models.CharField(choices=[('not_shipped', 'not_shipped'), ('preparing', 'preparing'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('returned', 'returned')], default='not_shipped', max_length=30)),
                ('tracking_code', models.CharField(blank=True, max_length=120)),
                ('address', models.JSONField(default=dict)),
                ('payment_reference', models.CharField(blank=True, max_length=160)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.PositiveBigIntegerField()),
                ('line_total', models.PositiveBigIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
