# Generated by Django 5.2.5 on 2026-08-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_image', models.URLField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('name', models.CharField(max_length=180)),
                ('persian_name', models.CharField(blank=True, max_length=180)),
                ('slug', models.SlugField(allow_unicode=True, max_length=220, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='brands/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_popular', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('wordpress_id', models.BigIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
    ]
