# Generated by Django 5.2.5 on 2026-08-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('canonicalUrl', models.URLField(blank=True)),
                ('robots', models.CharField(default='index, follow', max_length=80)),
                ('ogType', models.CharField(default='website', max_length=40)),
                ('ogImage', models.URLField(blank=True)),
                ('ogTitle', models.CharField(blank=True, max_length=255)),
                ('ogDescription', models.TextField(blank=True)),
                ('twitterCard', models.CharField(default='summary_large_image', max_length=40)),
                ('schemaJson', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
