# Generated by Django 5.2.5 on 2026-08-12 12:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_image', models.URLField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.TextField(blank=True)),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=64)),
                ('price', models.PositiveBigIntegerField(db_index=True)),
                ('discount_price', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('stock', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('volume_or_size', models.CharField(blank=True, max_length=120)),
                ('usage_instructions', models.TextField(blank=True)),
                ('ingredients', models.TextField(blank=True)),
                ('rating', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('sales_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_popular', models.BooleanField(db_index=True, default=False)),
                ('is_golden_offer', models.BooleanField(db_index=True, default=False)),
                ('badge', models.CharField(blank=True, max_length=80)),
                ('bg_glow_color', models.CharField(blank=True, max_length=80)),
                ('wordpress_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='brands.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='products/original/')),
                ('original_url', models.URLField(blank=True)),
                ('webp_image', models.ImageField(blank=True, upload_to='products/webp/')),
                ('alt', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('wordpress_attachment_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'category', 'brand'], name='products_pr_is_acti_9e683f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'price'], name='products_pr_is_acti_085b05_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'stock'], name='products_pr_is_acti_fec1f9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'is_active'], name='products_pr_is_feat_a1ecf6_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_primary', 'sort_order'], name='products_pr_product_7d975c_idx'),
        ),
    ]
