# Generated by Codex on 2026-08-15

from django.db import migrations, models


def backfill_null_attributes(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Product.objects.filter(attributes__isnull=True).update(attributes={})


class Migration(migrations.Migration):
    dependencies = [("products", "0001_initial")]

    operations = [
        migrations.RunPython(backfill_null_attributes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="product",
            name="attributes",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
