# Generated by Django 5.2.5 on 2026-08-12 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NavbarItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(allow_unicode=True, db_index=True, max_length=180, unique=True)),
                ("url", models.CharField(blank=True, max_length=500)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("icon", models.CharField(blank=True, max_length=120)),
                ("image_url", models.URLField(blank=True)),
                ("badge_text", models.CharField(blank=True, max_length=80)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="navbar.navbaritem",
                    ),
                ),
            ],
            options={"ordering": ("order", "id")},
        ),
        migrations.AddIndex(
            model_name="navbaritem",
            index=models.Index(fields=["parent", "is_active", "order", "id"], name="navbar_nav_parent__6c2ee0_idx"),
        ),
    ]
